### ISSUE TITLE
finish some summon monster card

### ISSUE THREAD

**Issue by realeternia** [realeternia/TOMClassic#32]

**Comment by narlon** [comment]
![Uploading 309.JPG…]()

**Comment by realeternia** [comment]
![309](https://cloud.githubusercontent.com/assets/11283130/14758844/411cd858-093f-11e6-969b-762fb4176a65.JPG)
![75](https://cloud.githubusercontent.com/assets/11283130/14758846/4f6f21b8-093f-11e6-829c-6426fe8b0b51.JPG)

**Comment by realeternia** [comment]
![205](https://cloud.githubusercontent.com/assets/11283130/14759222/08335874-094d-11e6-80b7-b9a95950adaf.JPG)

**Comment by realeternia** [comment]
![198](https://cloud.githubusercontent.com/assets/11283130/14759316/8054340a-0951-11e6-8533-a3db3122a5fb.JPG)
